//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWORLD开发助手.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tp_DL")]
        public string Tab_0 {
            get {
                return ((string)(this["Tab_0"]));
            }
            set {
                this["Tab_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tp_Debug")]
        public string Tab_1 {
            get {
                return ((string)(this["Tab_1"]));
            }
            set {
                this["Tab_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tp_Tools")]
        public string Tab_2 {
            get {
                return ((string)(this["Tab_2"]));
            }
            set {
                this["Tab_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tp_Code")]
        public string Tab_3 {
            get {
                return ((string)(this["Tab_3"]));
            }
            set {
                this["Tab_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int DL_BaudRate {
            get {
                return ((int)(this["DL_BaudRate"]));
            }
            set {
                this["DL_BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DL_File_Path {
            get {
                return ((string)(this["DL_File_Path"]));
            }
            set {
                this["DL_File_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int DL_BL_Go_Way {
            get {
                return ((int)(this["DL_BL_Go_Way"]));
            }
            set {
                this["DL_BL_Go_Way"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DL_BL_Auto_Match {
            get {
                return ((bool)(this["DL_BL_Auto_Match"]));
            }
            set {
                this["DL_BL_Auto_Match"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("08000000")]
        public string DL_Start_Address {
            get {
                return ((string)(this["DL_Start_Address"]));
            }
            set {
                this["DL_Start_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("08000000")]
        public string DL_Run_Address {
            get {
                return ((string)(this["DL_Run_Address"]));
            }
            set {
                this["DL_Run_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DL_Check {
            get {
                return ((bool)(this["DL_Check"]));
            }
            set {
                this["DL_Check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DL_After_Direct_Run {
            get {
                return ((bool)(this["DL_After_Direct_Run"]));
            }
            set {
                this["DL_After_Direct_Run"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DL_Auto_Close_Debug_Port {
            get {
                return ((bool)(this["DL_Auto_Close_Debug_Port"]));
            }
            set {
                this["DL_Auto_Close_Debug_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DL_Show_Time {
            get {
                return ((bool)(this["DL_Show_Time"]));
            }
            set {
                this["DL_Show_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DL_Auto_Download {
            get {
                return ((bool)(this["DL_Auto_Download"]));
            }
            set {
                this["DL_Auto_Download"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DL_Erase_Way {
            get {
                return ((int)(this["DL_Erase_Way"]));
            }
            set {
                this["DL_Erase_Way"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DL_Write_Option_Byte {
            get {
                return ((bool)(this["DL_Write_Option_Byte"]));
            }
            set {
                this["DL_Write_Option_Byte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5A")]
        public string DL_Read_Protect {
            get {
                return ((string)(this["DL_Read_Protect"]));
            }
            set {
                this["DL_Read_Protect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FF")]
        public string DL_HW_Byte {
            get {
                return ((string)(this["DL_HW_Byte"]));
            }
            set {
                this["DL_HW_Byte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FF")]
        public string DL_Write_Protect1 {
            get {
                return ((string)(this["DL_Write_Protect1"]));
            }
            set {
                this["DL_Write_Protect1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FF")]
        public string DL_Write_Protect2 {
            get {
                return ((string)(this["DL_Write_Protect2"]));
            }
            set {
                this["DL_Write_Protect2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FF")]
        public string DL_Write_Protect3 {
            get {
                return ((string)(this["DL_Write_Protect3"]));
            }
            set {
                this["DL_Write_Protect3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FF")]
        public string DL_Write_Protect4 {
            get {
                return ((string)(this["DL_Write_Protect4"]));
            }
            set {
                this["DL_Write_Protect4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FF")]
        public string DL_User_Data1 {
            get {
                return ((string)(this["DL_User_Data1"]));
            }
            set {
                this["DL_User_Data1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FF")]
        public string DL_User_Data2 {
            get {
                return ((string)(this["DL_User_Data2"]));
            }
            set {
                this["DL_User_Data2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Debug_BaudRate {
            get {
                return ((int)(this["Debug_BaudRate"]));
            }
            set {
                this["Debug_BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Debug_StopBit {
            get {
                return ((int)(this["Debug_StopBit"]));
            }
            set {
                this["Debug_StopBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Debug_DataBit {
            get {
                return ((int)(this["Debug_DataBit"]));
            }
            set {
                this["Debug_DataBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Debug_CheckBit {
            get {
                return ((int)(this["Debug_CheckBit"]));
            }
            set {
                this["Debug_CheckBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug_Show_Hex {
            get {
                return ((bool)(this["Debug_Show_Hex"]));
            }
            set {
                this["Debug_Show_Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug_DTR {
            get {
                return ((bool)(this["Debug_DTR"]));
            }
            set {
                this["Debug_DTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug_RTS {
            get {
                return ((bool)(this["Debug_RTS"]));
            }
            set {
                this["Debug_RTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Debug_RTS_Time {
            get {
                return ((int)(this["Debug_RTS_Time"]));
            }
            set {
                this["Debug_RTS_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Debug_Send_One {
            get {
                return ((string)(this["Debug_Send_One"]));
            }
            set {
                this["Debug_Send_One"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Debug_Send_File_Name {
            get {
                return ((string)(this["Debug_Send_File_Name"]));
            }
            set {
                this["Debug_Send_File_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug_Send_Hex {
            get {
                return ((bool)(this["Debug_Send_Hex"]));
            }
            set {
                this["Debug_Send_Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug_Send_NewLine {
            get {
                return ((bool)(this["Debug_Send_NewLine"]));
            }
            set {
                this["Debug_Send_NewLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug_Send_OnTime {
            get {
                return ((bool)(this["Debug_Send_OnTime"]));
            }
            set {
                this["Debug_Send_OnTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string Debug_Resend_Time {
            get {
                return ((string)(this["Debug_Resend_Time"]));
            }
            set {
                this["Debug_Resend_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug_Show_Time {
            get {
                return ((bool)(this["Debug_Show_Time"]));
            }
            set {
                this["Debug_Show_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string Debug_Show_Time_Val {
            get {
                return ((string)(this["Debug_Show_Time_Val"]));
            }
            set {
                this["Debug_Show_Time_Val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DL_Start_Address_Enable {
            get {
                return ((bool)(this["DL_Start_Address_Enable"]));
            }
            set {
                this["DL_Start_Address_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DL_Run_Address_Enable {
            get {
                return ((bool)(this["DL_Run_Address_Enable"]));
            }
            set {
                this["DL_Run_Address_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Frm_Fix_Stat {
            get {
                return ((bool)(this["Frm_Fix_Stat"]));
            }
            set {
                this["Frm_Fix_Stat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Frm_Max_Stat {
            get {
                return ((bool)(this["Frm_Max_Stat"]));
            }
            set {
                this["Frm_Max_Stat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 580")]
        public global::System.Drawing.Size Frm_Size {
            get {
                return ((global::System.Drawing.Size)(this["Frm_Size"]));
            }
            set {
                this["Frm_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataSet Debug_Send_Project {
            get {
                return ((global::System.Data.DataSet)(this["Debug_Send_Project"]));
            }
            set {
                this["Debug_Send_Project"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("默认项目")]
        public string Debug_Select_Prj_Name {
            get {
                return ((string)(this["Debug_Select_Prj_Name"]));
            }
            set {
                this["Debug_Select_Prj_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Debug_Select_Prj_Page {
            get {
                return ((int)(this["Debug_Select_Prj_Page"]));
            }
            set {
                this["Debug_Select_Prj_Page"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug_Send_M_NewLine {
            get {
                return ((bool)(this["Debug_Send_M_NewLine"]));
            }
            set {
                this["Debug_Send_M_NewLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug_Send_M_Hex {
            get {
                return ((bool)(this["Debug_Send_M_Hex"]));
            }
            set {
                this["Debug_Send_M_Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug_Send_M_ConNumKey {
            get {
                return ((bool)(this["Debug_Send_M_ConNumKey"]));
            }
            set {
                this["Debug_Send_M_ConNumKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug_Send_M_Resend {
            get {
                return ((bool)(this["Debug_Send_M_Resend"]));
            }
            set {
                this["Debug_Send_M_Resend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string Debug_Send_M_Resend_Time {
            get {
                return ((string)(this["Debug_Send_M_Resend_Time"]));
            }
            set {
                this["Debug_Send_M_Resend_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Start_Check_Update {
            get {
                return ((bool)(this["Start_Check_Update"]));
            }
            set {
                this["Start_Check_Update"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Version_Info {
            get {
                return ((bool)(this["Show_Version_Info"]));
            }
            set {
                this["Show_Version_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tp_Type")]
        public string Tab_4 {
            get {
                return ((string)(this["Tab_4"]));
            }
            set {
                this["Tab_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tp_Help")]
        public string Tab_5 {
            get {
                return ((string)(this["Tab_5"]));
            }
            set {
                this["Tab_5"] = value;
            }
        }
    }
}
